sell-quantity: 100

whitelisted-mobs:
- 'PIG_ZOMBIE'
- 'ENDERMAN'
- 'PIG'
- 'COW'
- 'VILLAGER'
- 'IRON_GOLEM'
- 'WITCH'
- 'CACTUS'
- 'SUGAR_CANE'
- 'TNT'
harvester-hoe-item:
  material: 'DIAMOND_HOE'
  name: '&e&l(!) &eHarvesterHoe &e&l(!)'
  lore:
  - '&fBreak sugar cane for 2x drops!'
  enchanted: true
  glasspane:
    enabled: false
    color: 'RED'
collector-item:
  material: 'BEACON'
  name: '&e&l(!) &cFaction Collector &e&l(!)'
  lore:
  - '&fPlace this down in a chunk and right click'
  - '&fon it to open the interface.'
  enchanted: true
  glasspane:
    enabled: false
    color: 'RED'
sell-wand-item:
  material: 'WOOD_HOE'
  name: '&e&l(!) &5SellWand &e&l(!)'
  lore:
  - '&fClick on a faction collector to sell all the mobs!'
  enchanted: true
  glasspane:
    enabled: false
    color: 'RED'
tnt-wand-item:
  material: 'DIAMOND_HOE'
  name: '&e&l(!) &5TNTWand &e&l(!)'
  lore:
  - '&fClick on a faction collector to deposit all TNT to your TNTBank!'
  enchanted: true
  glasspane:
    enabled: false
    color: 'RED'
background-item:
  material: 'STAINED_GLASS_PANE'
  name: ' '
  lore: []
  enchanted: true
  glasspane:
    enabled: true
    color: 'RED'
help-item:
  material: 'BOOK'
  name: '&eInfo'
  lore:
  - '&eFaction Collectors allow you to easily store and sell'
  - '&emobs for money, along with gathering tnt from creepers and'
  - '&ethe harvesting of Cactus and Sugar Cane.'
  enchanted: false
  glasspane:
    enabled: false
    color: 'RED'
gui:
  title: '&cFaction Collector'
  item-template:
    name: '&e&l(!) &f{mob} &e&l(!)'
    lore:
    - '&eYou have &c{amount} available to sell.'
sell-values:
  pig-zombie: 17.0
  enderman: 14.0
  cow: 8.0
  pig: 5.0
  villager: 20.0
  iron-golem: 25.0
  witch: 20.0
  cactus: 2.0
  sugar-cane: 4.0
